parserOptions:
    sourceType: module

env:
    browser: true
    node: true
    es6: true

extends: [eslint:recommended]

rules:
    eqeqeq: 1
    semi: 1
    radix: 2
    quotes: [1, single]
    new-cap: 1
    arrow-parens: [1, as-needed]
    no-console: 1
